import Form from "react-bootstrap/Form";
import Col from "react-bootstrap/Col";
import Row from "react-bootstrap/Row";

import { useContext, useEffect } from "react";

import { GlobalContext } from "../../context/GlobalContext";
import { hexToRGB, rgbToHex } from "../../utils/colors";
import addEventListenerTo from "../../utils/addEventListenerTo";

/**
 * Provides the form for tag information input. The user can input 
 * the name and the color of the tag. The name input field is a 
 * Bootstrap `Form.Control`-component while the color input uses 
 * the basic `input`-tag of `type` "color". All tag names must be 
 * in uppercase and contain no spaces, tabs or newline characters; 
 * rules which are also enforced by this component.
 * 
 * Unlike the `ArticleForm`, the tag form usually provides the user 
 * with the added functionality of being able to remove the tag.
 * However, this functionality is not provided by this component, 
 * rather, it is declared by a creator function in `modals/create/
 * tag/createTagPopup` and rendered by the `FormModal`-component.
 * 
 * The information of the form is provided via the `data`-prop and can 
 * be manipulated via the hooks found in `setters`-prop.
 */
export default function TagForm(props) {
  const { tagName, tagColor } = props.data;
  const { setTagName, setTagColor, setContentChanged } = props.setters;
  const { r, g, b } = tagColor;
  const { languageManager: lm } = useContext(GlobalContext);
  const { actionSubmitChanges } = props.actions;
  const resetContentChangeFlag = props.resetContentChangeFlag;

  useEffect(() => {
    return addEventListenerTo(document, {
      type: "keydown",
      listener: handleSpecialKeys
    })
  }, [tagName, r, g, b]);

  /**
   * Called when the tag name input changes. Enforces the tag naming 
   * rules and updates the parent component.
   * 
   * @param {JSON} e Event-object from the onChange-event of the 
   * name input field.
   */
  const onChange = (e) => {
    setTagName(e.target.value.toUpperCase().replace(/\s/g, ""));
  };

    /**
   * Handles the presses of special keys such as shortcuts.
   * 
   * @param {JSON} e Event-object generated by the "keydown"-
   * event listening for special key presses.
   */
  const handleSpecialKeys = (e) => {
    if( e.ctrlKey )
    {
      const shortcutKey = e.key.toLowerCase()
      
      switch( shortcutKey )
      {
        case "s": actionSubmitChanges({ resetContentChangeFlag }); break;
      }
    }
  };

    /**
   * Handles a change by updating the parent component as well as 
   * notifiying it of the changed content. This way, when the content
   * changes, the control buttons that may be reacting to changes 
   * will also be updated.
   * 
   * @param {Function} change The change itself as a function.
   */
  const handleChange = (change) => {
    change();
    setContentChanged(true);
  };

  return (
    <Form onSubmit={(e) => e.preventDefault()}>
      <Row>
        <Col
          className="d-flex align-items-center"
          xs="2"
        >
          <b>{lm.translate("forms.tag-form.name")}: </b>
        </Col>
        <Col>
          <Form.Control
            value={tagName.toUpperCase().replace(/\s/g, "")}
            onChange={(e) => handleChange(() => onChange(e))}
          />
        </Col>
        <Col className="d-flex align-items-center">
          <input
            type="color"
            value={"#" + rgbToHex(r, g, b)}
            onChange={(e) => handleChange(() => setTagColor(hexToRGB(e.target.value, true)))}
          />
        </Col>
      </Row>
    </Form>
  );
}
